### PR TITLE
PR - Code Review - Linter setup and gitignore

### PR DESCRIPTION
**Pull request by Destin-Lupaya**
- Configured Linters into the project.
- Followed the recommended github flow.
- Update Readme file to describe the project.
- Added Toolbar and Headline sections.

### CODE REVIEW

**Review by LionRouge1 — COMMENTED** [review]
Hi @Destin-Lupaya, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have linters set up correctly, kindly make sure all the linters passed and are green before you submit your project for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by ademibowale — COMMENTED** [review]
Hi @LionRouge1 ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request




Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

You have submitted a project,that all linters check was not successfully passed, doesn't have linters set up correctly, kindly make sure all the linters passed and are green before you submit your project for review.please use this [Template](https://github.com/microverseinc/linters),

**Comment by TuyishimireEric** [comment]
# INVALID ❌ ❌ ❌
### Hi @Destin-Lupaya 👋

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Code Review Request ❌
You have submitted a project that has failing Linters 😨, Kindly fix Linters and submit again once you are done 🙏  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Kindly create  a new PR that follows the Gitflow approach

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

---
_Invalid Code Review Request does not count into the code reviews limit._

**Review by joel-kalema — COMMENTED** [review]
Hi @

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project that has linters that does not pass, make sure you solve them and the ask again for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AdnanOlarmmi** [comment]
Hi @Destin-Lupaya,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid Code Review Request
 You have submitted a project that has linters that does not pass, make sure you solve them and the ask again for a review
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request does not count into the code reviews limit.

**Pull request merged**
